name: CI pipeline 
on: 
  
  pull_request:
    branches:
      - main
env:
  App_ENV: production
  loglevel: debug
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: echo "Checking out code..."
            - name: list folders
              run: ls -la
            - name: print workflow event
              run: echo "${{ github.event_name }}"
            - name: print github os 
              run: echo "${{ runner.os }}"
            - name: print github repo
              run: echo "${{ github.repository }}"
            - name: print App_ENV
              run: echo "${{ env.App_ENV }}"
            - name: print loglevel
              run: echo "${{ env.loglevel }}"
            - name: Github secret 
              run: echo " secret is ${{ secrets.SECRET_MESSAGE }}"