name: Docker Build (CI)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOCKEN }}
      - name: Build docker hub image 
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:ci .
      - name: Push docker Image 
        run: |
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:ci

    
    ##           uses: docker/setup-qemu-action@v3

     #
     # name: Build Docker image
      #  uses: docker/build-push-action@v5
       # with:
        #  context: .
         # file: ./Dockerfile
          #platforms: linux/amd64
         # push: false
         # tags: myapp:ci